<?php

/**
 * Implements hook_menu().
 *
 * Retrieve contacts from civicrm for autocomplete widget.
 */
function civicrm_contact_ref_menu() {
  $items = array();
  $items['civicrm_contact_ref/autocomplete'] = array(
    'title' => 'Contacts',
    'page callback' => 'civicrm_contact_ref_autocomplete_value',
    'delivery callback' => 'backdrop_json_deliver',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_field_info().
 */
function civicrm_contact_ref_field_info() {
  return array(
    'civicrm_contact_ref_contact' =>
    array(
      'label' => t('CiviCRM Contact'),
      'description' => t('Reference a CiviCRM contact.'),
      'default_widget' => 'options_select',
      'default_formatter' => 'civicrm_contact_ref_link',
      // note that this property is used by entity.module
      'property_type' => 'integer',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function civicrm_contact_ref_field_widget_info() {
  return array(
    'civicrm_contact_ref_autocomplete' =>
    array(
      'label' => t('Autocomplete text field'),
      'field types' => array('civicrm_contact_ref_contact'),
      'settings' => array(
        'size' => 60,
        'autocomplete_path' => 'civicrm_contact_ref/autocomplete',
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_info_alter().
 */
function civicrm_contact_ref_field_widget_info_alter(&$info) {
  $info['options_select']['field types'][] = 'civicrm_contact_ref_contact';
  $info['options_buttons']['field types'][] = 'civicrm_contact_ref_contact';
}

/**
 * Implements hook_options_list().
 */
function civicrm_contact_ref_options_list($field, $instance, $entity_type, $entity) {
  $function = !empty($field['settings']['options_list_callback']) ? $field['settings']['options_list_callback'] : 'civicrm_contact_ref_options_list_values';
  return $function($field, $instance, $entity_type, $entity);
}

/**
 * Implements hook_field_is_empty().
 */
function civicrm_contact_ref_field_is_empty($item, $field) {
  return empty($item['contact_id']) ? TRUE : FALSE;
}

/**
 * Implements hook_field_formatter_info().
 */
function civicrm_contact_ref_field_formatter_info() {
  return array(
    'civicrm_contact_ref_link' => array(
      'label' => t('Title (link)'),
      'field types' => array('civicrm_contact_ref_contact'),
    ),
    'civicrm_contact_ref_plain' => array(
      'label' => t('Title (plain)'),
      'field types' => array('civicrm_contact_ref_contact'),
    ),
    'civicrm_contact_ref_raw' => array(
      'label' => t('CID (raw)'),
      'field types' => array('civicrm_contact_ref_contact'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function civicrm_contact_ref_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // Terms whose tid is 'autocreate' do not exist
  // yet and $item['taxonomy_term'] is not set. Theme such terms as
  // just their name.

  switch ($display['type']) {
    case 'civicrm_contact_ref_link':
      foreach ($items as $delta => $item) {
        if (isset($item['contact_id']) && is_numeric($item['contact_id'])) {
          $title = _civicrm_contact_ref_titles($item['contact_id']);
          $element[$delta] = array(
            '#markup' => l($title,
              'civicrm/contact/view',
              array(
                'query' =>
                array(
                  'reset' => 1,
                  'cid' => "{$item['contact_id']}",
                ),
              )
            ),
          );
        }
      }
      break;

    case 'civicrm_contact_ref_plain':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#markup' => _civicrm_contact_ref_titles($item['contact_id']),
        );
      }
      break;

    case 'civicrm_contact_ref_raw':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#markup' => $item['contact_id'],
        );
      }
      break;
  }

  return $element;
}

/**
 * Returns the set of valid civicrm contacts
 *
 * @param array $field
 *   The field definition.
 * @param array $instance
 *   A field instance array.
 * @param string $entity_type
 *   The type of entity; e.g. 'node' or 'user'.
 * @param EntityInterface|null $entity
 *   The entity object or NULL if the entity hasn't been created yet.
 *
 * @return array
 *   The array of valid contacts.
 */
function civicrm_contact_ref_options_list_values($field, $instance, $entity_type, $entity) {
  $entity_id = NULL;
  if ($entity) {
    $entity_id = $entity->id();
  }

  $references = _civicrm_contact_ref_potential_references($field['field_name'], $entity_type, $instance['bundle'], $entity_id);

  $options = array();
  foreach ($references as $key => $value) {
    // Views theming runs check_plain (htmlentities) on the values.
    // We reverse that with html_entity_decode.
    $options[$key] = html_entity_decode(strip_tags($value['rendered']));
  }
  return $options;
}

/**
 * Implements hook_field_widget_form().
 */
function civicrm_contact_ref_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $defaultValues = array();
  foreach ($items as $item) {
    $sort_name = _civicrm_contact_ref_titles($item['contact_id'], 'sort_name');
    $defaultValues[] = "$sort_name [cid:{$item['contact_id']}]";
  }

  $entity = isset($element['#entity']) ? $element['#entity'] : NULL;

  $autocomplete_path = $instance['widget']['settings']['autocomplete_path'] . '/' . $field['field_name'] . '/' . $instance['entity_type'] . '/' . $instance['bundle'] . '/';

  // Use <NULL> as a placeholder in the URL when there's no entity.
  // Most webservers collapse two consecutive slashes.
  $entity_id = 'NULL';
  if ($entity) {
    $entity_id = $entity->id();
  }
  $autocomplete_path .= $entity_id;

  $element += array(
    '#type' => 'textfield',
    '#autocomplete_path' => $autocomplete_path,
    '#size' => $instance['widget']['settings']['size'],
    '#maxlength' => 1024,
    '#default_value' => empty($defaultValues[$delta]) ? '' : $defaultValues[$delta],
    '#element_validate' => array('civicrm_contact_ref_autocomplete_validate'),
  );

  return array('contact_id' => $element);
}

/**
 * Implements hook_field_widget_error().
 */
function civicrm_contact_ref_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element, $error['message']);
}

/**
 * Implements hook_field_settings_form().
 */
function civicrm_contact_ref_field_settings_form($field, $instance, $has_data) {

  if (!civicrm_initialize()) {
    return;
  }

  $settings = $field['settings'];

  require_once 'CRM/Contact/BAO/ContactType.php';
  $contactTypes = CRM_Contact_BAO_ContactType::basicTypePairs();
  $form = array();
  $form['allowed_values'] = array(
    '#tree' => TRUE,
  );
  foreach ($contactTypes as $name => $label) {
    $subTypes = CRM_Contact_BAO_ContactType::subTypePairs($name);
    $form['allowed_values'][$name] = array(
      '#type' => 'checkboxes',
      '#title' => ts('CiviCRM Contact Type %1', array(1 => $label)),
      '#options' => CRM_Utils_Array::crmArrayMerge(array($name => $label), $subTypes),
      '#default_value' => isset($settings['allowed_values']) ? $settings['allowed_values'][$name] : array(),
      '#weight' => 1,
      '#access' => empty($settings['options_list_callback']) && empty($settings['allowed_values_function']),
    );
  }

  $form['custom_callbacks'] = array(
    '#type' => 'item',
    '#title' => t('Custom callbacks'),
    '#markup' => t('Custom callback functions can be used to fetch the values for this field. This is useful if values need more customized filtering than selecting by Contact Types. The <code>options_list_callback</code> setting will a custom function that returns a list to be displayed in an options list. The <code>allowed_values_function</code> setting returns references used for the allowed values. It will be used for all widgets: autocomplete and list. It will also be used for validation. Consult <em>civicrm_contact_ref.api.php</em> in the module for more info.'),
    '#access' => empty($settings['options_list_callback']) && empty($settings['allowed_values_function']),
  );

  $form['allowed_values_function'] = array(
    '#type' => 'value',
    '#value' => !empty($settings['allowed_values_function']) ? $settings['allowed_values_function'] : '',
  );
  $form['allowed_values_function_display'] = array(
    '#type' => 'item',
    '#title' => t('Allowed values list'),
    '#markup' => t('The value of this field is being determined by the <code>@function</code> function in the <em>allowed_values_callback</em> field setting and cannot be changed here. Consult <em>civicrm_contact_ref.api.php</em> for more info.', array('@function' => !empty($settings['allowed_values_function']) ? $settings['allowed_values_function'] : '')),
    '#access' => !empty($settings['allowed_values_function']),
  );

  $form['options_list_callback'] = array(
    '#type' => 'value',
    '#value' => !empty($settings['options_list_callback']) ? $settings['options_list_callback'] : '',
  );
  $form['options_list_callback_display'] = array(
    '#type' => 'item',
    '#title' => t('Options list'),
    '#markup' => t('The values of this field are being determined by the <code>@function</code> function in the field setting <em>options_list_callback</em> and cannot not be changed here. Consult <em>civicrm_contact_ref.api.php</em> for more info.', array('@function' => !empty($settings['options_list_callback']) ? $settings['options_list_callback'] : '')),
    '#access' => !empty($settings['options_list_callback']),
  );

  return $form;
}

/**
 * Form element validate handler for civicrm contact autocomplete element.
 */
function civicrm_contact_ref_autocomplete_validate($element, &$form_state) {

  $value     = $element['#value'];
  $entity = isset($element['#entity']) ? $element['#entity'] : NULL;
  $entity_id = NULL;
  if ($entity) {
    $entity_id = $entity->id();
  }

  $cid = NULL;
  if (!empty($value)) {
    preg_match('/^(?:\s*|(.*) )?\[\s*cid\s*:\s*(\d+)\s*\]$/', $value, $matches);
    if (!empty($matches)) {
      // Explicit [cid:n].
      $cid = $matches[2];
    }
    else {
      // No explicit cid.
      $cids = _civicrm_contact_ref_potential_references($element['#field_name'], $element['#entity_type'], $element['#bundle'], $entity_id, $value, TRUE);
      if (empty($cids)) {
        form_error($element, t('%name: found no valid post with that title.', array('%name' => $element['#title'])));
      }
      else {
        // TODO:
        // the best thing would be to present the user with an additional form,
        // allowing the user to choose between valid candidates with the same title
        // ATM, we pick the first matching candidate...
        $cid = array_shift(array_keys($cids));
      }
    }
  }

  form_set_value($element, $cid, $form_state);
}

/**
 * Menu callback to provide values for autocomplete civicrm contact
 * element, depends upon entered string.
 *
 * @param string $field_name
 *   The name of the contact reference field.
 * @param string $entity_type
 *   The entity type.
 * @param string $bundle_name
 *   The bundle name.
 * @param string $entity_id
 *   The entity ID the contact reference field is attached to, or an empty
 *   string if the entity hasn't been created yet.
 * @param string $string
 *   The label of the Contact to query by.
 */
function civicrm_contact_ref_autocomplete_value($field_name, $entity_type, $bundle_name, $entity_id = '', $string = '') {
  if (!civicrm_initialize()) {
    return;
  }

  // If the request has a '/' in the search text, then the menu system will have
  // split it into multiple arguments and $string will only be a partial.
  // Make sure to recover the intended $string.
  $args = func_get_args();
  // Shift off the $type, $field_name, $entity_type,
  // $bundle_name, and $entity_id args.
  array_shift($args);
  array_shift($args);
  array_shift($args);
  array_shift($args);
  array_shift($args);
  $string = implode('/', $args);

  $matches = array();

  $references = _civicrm_contact_ref_potential_references($field_name, $entity_type, $bundle_name, $entity_id, $string);
  foreach ($references as $id => $row) {
    // Add a class wrapper for a few required CSS overrides.
    $matches["{$row['title']} [cid:{$id}]"] = '<div class="reference-autocomplete">' . $row['rendered'] . '</div>';
  }
  backdrop_json_output($matches);
}

/**
 * Fetch an array of all candidate referenced nodes.
 *
 * This info is used in various places (allowed values, autocomplete results,
 * input validation...). Some of them only need the nids, others nid + titles,
 * others yet nid + titles + rendered row (for display in widgets).
 * The array we return contains all the potentially needed information, and lets
 * consumers use the parts they actually need.
 *
 * @param string $field_name
 *   The name of the contact reference field.
 * @param string $entity_type
 *   The entity type.
 * @param string $bundle_name
 *   The bundle name.
 * @param string|null $entity_id
 *   The entity ID the contact reference field is attached to, or an empty
 *   string if the entity hasn't been created yet.
 * @param string $string
 *   Optional string to filter titles on (used by autocomplete)
 * @param bool $exact_string
 *   Should the title filter be an exact match. Defaults to FALSE.
 *
 * @return array
 *   An array of valid nodes in the form:
 *   array(
 *     nid => array(
 *       'title' => The node title,
 *       'rendered' => The text to display in widgets (can be HTML)
 *     ),
 *     ...
 *   )
 */
function _civicrm_contact_ref_potential_references($field_name, $entity_type, $bundle_name, $entity_id, $string = '', $exact_string = FALSE) {
  static $results = array();

  $field = field_info_field($field_name);

  $function = !empty($field['settings']['allowed_values_function']) ? $field['settings']['allowed_values_function'] : '_civicrm_contact_ref_potential_references_standard';
  $references = $function($field_name, $entity_type, $bundle_name, $entity_id, $string, $exact_string);

  // Store the results.
  $results[$field['field_name']][$string][$exact_string] = $references;

  return $results[$field['field_name']][$string][$exact_string];
}

/**
 * Helper function for referenceable CiviCRM contacts.
 *
 * @param string $field_name
 *   The name of the contact reference field.
 * @param string $entity_type
 *   The entity type.
 * @param string $bundle_name
 *   The bundle name.
 * @param string|null $entity_id
 *   The entity ID the contact reference field is attached to, or an empty
 *   string if the entity hasn't been created yet.
 * @param string $string
 *   Optional string to filter titles on (used by autocomplete)
 * @param bool $exact_string
 *   Should the title filter be an exact match. Defaults to FALSE.
 *
 * @return array
 *   Nested array of references keyed by the contact ID containing an array of
 *   the contact title and the rendered contact info to display.
 *
 * @see _civicrm_contact_ref_potential_references()
 */
function _civicrm_contact_ref_potential_references_standard($field_name, $entity_type, $bundle_name, $entity_id, $string = '', $exact_string = FALSE) {
  $args = $whereClause = $contactTypes = $contactSubTypes = array();
  $limit = '10';

  if (!civicrm_initialize()) {
    return;
  }

  $field = field_info_field($field_name);

  require_once 'CRM/Contact/BAO/ContactType.php';
  $basicTypes = CRM_Contact_BAO_ContactType::basicTypePairs();

  foreach ($basicTypes as $name => $label) {
    if (isset($field['settings']['allowed_values']) && is_array($field['settings']['allowed_values'][$name])) {
      $contactNames = array_filter($field['settings']['allowed_values'][$name]);
      if (!empty($contactNames)) {
        if (in_array($name, $contactNames)) {
          $contactTypes[] = $name;
        }
        else {
          $contactSubTypes = array_merge($contactSubTypes, array_keys($contactNames));
        }
      }
    }
  }

  if (!empty($contactTypes)) {
    $contactTypes = implode("','", $contactTypes);
    $whereClause[] = "contact_type IN ( '{$contactTypes}' )";
  }

  if (!empty($contactSubTypes)) {
    foreach ($contactSubTypes as $subType) {
      $whereClause[] = "contact_sub_type LIKE '%" . CRM_Core_DAO::VALUE_SEPARATOR . $subType . CRM_Core_DAO::VALUE_SEPARATOR . "%'";
    }
  }

  $whereClause = empty($whereClause) ? '' : '(' . implode(' OR ', $whereClause) . ') AND';

  if (isset($string)) {
    if ($exact_string) {
      $string_clause = " AND sort_name = %1";
      $args[] = $string;
    }
    else {
      $string_clause = " AND sort_name LIKE %1";
      $args[] = "%%" . $string . "%";
    }
  }

  $q = "
    SELECT sort_name, id
    FROM civicrm_contact
    WHERE $whereClause
    sort_name IS NOT NULL
    AND sort_name NOT LIKE ''
    AND sort_name NOT LIKE '<Last>%%'
    AND sort_name NOT LIKE '%@%%'
    AND sort_name NOT LIKE '--%%'
    AND sort_name NOT LIKE '- -%%'
    AND sort_name NOT LIKE ',%%'
    AND sort_name NOT LIKE '..%%'
    AND is_deleted = 0
    " . $string_clause . " LIMIT $limit";
  $params = array(1 => array($args[0], "String"));
  $dao = CRM_Core_DAO::executeQuery($q, $params);

  $references = array();
  while ($dao->fetch()) {
    $references[$dao->id] = array(
      'title' => $dao->sort_name,
      'rendered' => $dao->sort_name,
    );
  }

  return $references;
}

/**
 * Helper function for formatters.
 *
 * Store node titles collected in the current request.
 *
 * @param int $cid
 * @param string $field
 *
 * @return string|null
 */
function _civicrm_contact_ref_titles($cid, $field = 'display_name') {
  if (!civicrm_initialize() || !$cid) {
    return NULL;
  }
  static $titles = array();

  if (!isset($titles["{$cid}_{$field}"])) {
    $q = "
SELECT {$field}
FROM   civicrm_contact
WHERE  id = %1";
    $params = array(1 => array($cid, "Integer"));
    $dao = CRM_Core_DAO::executeQuery($q, $params);

    $titles["{$cid}_{$field}"] = $dao->fetch() ? $dao->$field : '';
  }
  return $titles["{$cid}_{$field}"];
}

/**
 * Implements hook_field_views_data().
 *
 * To allow for views relationships
 */
function civicrm_contact_ref_field_views_data($field) {
  $data = field_views_field_default_views_data($field);
  $storage = $field['storage']['details']['sql'];

  foreach ($storage as $age => $table_data) {
    $table = key($table_data);
    $columns = current($table_data);
    $id_column = $columns['contact_id'];
    if (isset($data[$table])) {
      // Relationship.
      $data[$table][$id_column]['relationship'] = array(
        'handler' => 'views_handler_relationship',
        'base' => 'civicrm_contact',
        'base field' => 'id',
        'field' => $id_column,
        'label' => $field['field_name'],
        'field_name' => $field['field_name'],
      );
    }
  }

  return $data;
}

/**
 * Implements hook_civicrm_merge().
 *
 * Update field data to reflect new cids when contacts are merged.
 */
function civicrm_contact_ref_civicrm_merge($type, $data, $new_id = NULL, $old_id = NULL, $tables = NULL) {
  $updated = FALSE;
  if (!empty($new_id) && !empty($old_id) && $type == 'sqls' && $tables === FALSE) {
    // Update contact reference field data
    $field_config_names = config_get_names_with_prefix('field.field.');
    foreach ($field_config_names as $config_name) {
      $field_config = config($config_name);
      if ($field_config->get('module') != 'civicrm_contact_ref') {
        continue;
      }
      $field_name = $field_config->get('field_name');
      $result = db_update("field_data_{$field_name}")
        ->fields(array("{$field_name}_contact_id" => $new_id))
        ->condition("{$field_name}_contact_id", $old_id)
        ->execute();
      $result = db_update("field_revision_{$field_name}")
        ->fields(array("{$field_name}_contact_id" => $new_id))
        ->condition("{$field_name}_contact_id", $old_id)
        ->execute();
      if ($result) {
        $updated = TRUE;
      }
    }
  }
  if ($updated) {
    cache_flush('cache_field');
    cache_flush('cache_page');
  }
}

