# Backdrop recipe
name: borg
recipe: backdrop
config:
  php: '7.2'
  webroot: www
  backdrush: 1.3.0
  xdebug: true
services:
  database:
    type: mariadb:10.3
    portforward: 3308
  cache:
    type: redis
    persist: true
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://borg.lndo.site
  redis-cli:
    service: cache
