# Backdrop recipe
name: borg

# Start with the default Backdrop recipe
recipe: backdrop

# Configure the Backdrop recipe
config:

  # See: https://backdropcms.org/requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Backdrop.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Backdrop 6 so YMMV.
  #
  # See: https://backdropcms.org/requirements
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.0'

  # Optionally specify whether you want to serve Backdrop via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://backdropcms.org/requirements
  #
  # via: nginx

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  #
  webroot: www

  # Optionally specify the version of Backdrush you want for your site
  #
  # This can be either
  #   - `stable`
  #   - `dev`
  #   - `any valid git ref for which there will be a github download` eg 0.0.3
  #
  # If ommitted this will use the stable Backdrush.
  #
  backdrush: stable

  # Optionally activate xdebug
  xdebug: true

  # Optionally mix in your own config files
  #
  # If ommitted this will use the default Backdrop config files for the respective
  # services.
  #
  # Definitely consult the relevant documentaion for each service to make sure
  # you are specifying the correct value for the config.
  #
  # conf:
    # server: config/backdrop.conf
    # database: config/mysql
    # php: config/php.ini


# The Backdrop recipe is super slick but we want to augment this recipe so we can
# run our front end tooling magix
services:
  database:
    type: mariadb
    portforward: 3308
  node:
    type: node:6.10
  cache:
    type: redis
    persist: true
tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
