name: borg
recipe: backdrop
env_file:
  - .env
config:
  php: '7.2'
  webroot: www
  backdrush: 1.x-1.x
  xdebug: true
services:
  database:
    type: mariadb:10.3
    portforward: 3308
  cache:
    type: redis
    persist: true
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://borg.lndo.site
  redis-cli:
    service: cache
  pull-db:
    service: appserver
    description: 'Get the latest DB from backdropcms.org'
    cmd:
      - appserver: php /app/scripts/pull-db-files.php --database
      - database: /helpers/sql-import.sh backdropcmsorg-latest-sanitized.sql.gz
      - appserver: rm -f backdropcmsorg-latest-sanitized.sql.gz
  pull-files:
    service: appserver
    description: 'Get the latest files from backdropcms.org'
    cmd:
      - php /app/scripts/pull-db-files.php --files
      - tar -xzf backdropcmsorg-files-latest.tar.gz
      - rm -r www/files/ && mv files/ www/
      - rm -f backdropcmsorg-files-latest.tar.gz
  phpcs:
    service: appserver
    cmd:
      - "/app/vendor/bin/phpcs -n --report=full --standard=Backdrop --ignore=vendor/*,README.md --extensions=install,module,php,inc,theme"
