<?php
/**
 * @file
 * Adds user profile links to the sitemap.
 */

/**
 * Implements hook_autoload_info().
 */
function xmlsitemap_user_autoload_info() {
  return array(
    // Tests.
    'XMLSitemapUserFunctionalTest' => 'tests/xmlsitemap_user.test',
  );
}

/**
 * @file
 * Default file for XML sitemap user.
 */

/**
 * Implements hook_entity_info_alter().
 */
function xmlsitemap_user_entity_info_alter(&$entity_info) {
  $entity_info['user']['bundle label'] = t('User');
  $entity_info['user']['xmlsitemap'] = array(
    'process callback' => 'xmlsitemap_user_xmlsitemap_process_user_links',
  );
}

/**
 * Implements hook_xmlsitemap_link_info().
 */
function xmlsitemap_user_xmlsitemap_link_info() {
  $info = array();
  $entity_info = entity_get_info();
  if (isset($entity_info['user'])) {
    $info['user'] = $entity_info['user'];
  }

  return $info;
}

/**
 * Implements hook_xmlsitemap_operation_link_alter().
 */
function xmlsitemap_user_xmlsitemap_operation_link_alter(&$link) {
  // The XML Sitemap settings for the user entity are stored in a different
  // place than entity_get_info() returns.
  if ($link['href'] === 'admin/config/search/xmlsitemap/settings/user/user') {
    $link['href'] = 'admin/config/people/settings';
  }
}

/**
 * Implements hook_cron().
 *
 * Process old users not found in the {xmlsitemap} table.
 */
function xmlsitemap_user_cron() {
  xmlsitemap_user_xmlsitemap_index_links(config_get('xmlsitemap.settings', 'batch_limit'));
}

/**
 * Implements hook_xmlsitemap_index_links().
 */
function xmlsitemap_user_xmlsitemap_index_links($limit) {
  $uids = db_query_range("SELECT u.uid FROM {users} u LEFT JOIN {xmlsitemap} x ON x.type = 'user' AND u.uid = x.id WHERE x.id IS NULL AND u.uid > 0 ORDER BY u.uid DESC", 0, $limit)->fetchCol();
  xmlsitemap_user_xmlsitemap_process_user_links($uids);
}

/**
 * Process user sitemap links.
 *
 * @param array $uids
 *   An array of user IDs.
 */
function xmlsitemap_user_xmlsitemap_process_user_links(array $uids) {
  $accounts = user_load_multiple($uids);
  foreach ($accounts as $account) {
    $link = xmlsitemap_user_create_link($account);
    xmlsitemap_link_save($link, array($link['type'] => $account));
  }
}

/**
 * Implements hook_user_presave().
 */
function xmlsitemap_user_user_presave($account) {
  if (!empty($account->uid)) {
    $link = xmlsitemap_user_create_link($account);
    if (isset($account->xmlsitemap)) {
      $link = $account->xmlsitemap + $link;
      unset($account->xmlsitemap);
    }
    xmlsitemap_link_save($link, array($link['type'] => $account));
  }
}

/**
 * Implements hook_user_insert().
 */
function xmlsitemap_user_user_insert($account) {
  $link = xmlsitemap_user_create_link($account);
  xmlsitemap_link_save($link, array($link['type'] => $account));
}

/**
 * Implements hook_user_update().
 */
function xmlsitemap_user_user_update($account) {
  $link = xmlsitemap_user_create_link($account);
  xmlsitemap_link_save($link, array($link['type'] => $account));
}

/**
 * Implements hook_user_delete().
 */
function xmlsitemap_user_user_delete($account) {
  xmlsitemap_link_delete('user', $account->uid);
}

/**
 * Implements hook_field_extra_fields().
 */
function xmlsitemap_user_field_extra_fields() {
  $extras['user']['user']['form']['xmlsitemap'] = array(
    'label' => t('XML sitemap'),
    'description' => t('XML sitemap module element'),
    'weight' => 30,
  );
  return $extras;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see user_admin_settings()
 * @see xmlsitemap_add_link_bundle_settings()
 */
function xmlsitemap_user_form_user_profile_form_alter(&$form, $form_state) {
  // Add the link options.
  module_load_include('inc', 'xmlsitemap', 'xmlsitemap.admin');
  xmlsitemap_add_form_link_options($form, 'user', 'user', $form['#user']->uid);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see user_admin_settings()
 * @see xmlsitemap_add_link_bundle_settings()
 */
function xmlsitemap_user_form_user_admin_settings_alter(&$form, $form_state) {
  module_load_include('inc', 'xmlsitemap', 'xmlsitemap.admin');
  xmlsitemap_add_link_bundle_settings($form, $form_state, 'user', 'user');

  // @todo Figure out what this was supposed to do.
  // The array += operator causes a fatal error since both of those arrays can
  // be missing.
  // I don't see anything about an email on admin/config/people/settings.
  // $form['email_title'] += array('#weight' => 10);
  // $form['email'] += array('#weight' => 10);
}

/**
 * Create a sitemap link from a user.
 *
 * The link will be saved as $account->xmlsitemap.
 *
 * @param object $account
 *   A user object.
 */
function xmlsitemap_user_create_link(stdClass &$account) {
  if (!isset($account->xmlsitemap)) {
    $account->xmlsitemap = array();
    if ($account->uid && $link = xmlsitemap_link_load('user', $account->uid)) {
      $account->xmlsitemap = $link;
    }
  }

  $settings = xmlsitemap_link_bundle_load('user', 'user');
  $uri = entity_uri('user', $account);

  $account->xmlsitemap += array(
    'type' => 'user',
    'id' => $account->uid,
    'subtype' => 'user',
    'status' => $settings['status'],
    'status_default' => $settings['status'],
    'status_override' => 0,
    'priority' => $settings['priority'],
    'priority_default' => $settings['priority'],
    'priority_override' => 0,
  );

  // The following values must always be checked because they are volatile.
  $account->xmlsitemap['loc'] = $uri['path'];
  $account->xmlsitemap['access'] = $account->uid && $account->status;
  $account->xmlsitemap['language'] = !empty($account->language) ? $account->language : LANGUAGE_NONE;

  return $account->xmlsitemap;
}

/**
 * Implements hook_variables().
 */
function xmlsitemap_user_variables() {
  $defaults = array();
  return $defaults;
}
