<?php
/**
 * @file
 * Customise Tugboat pages/forms.
 */

/**
 * Implements hook_theme_registry_alter().
 *
 * @see https://api.backdropcms.org/documentation/overriding-template-files-in-a-module
 */
function borg_tugboat_theme_registry_alter(&$theme_registry) {
  $module_path = backdrop_get_path('module', 'borg_tugboat') . '/templates';
  $template_file_objects = backdrop_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  foreach ($template_file_objects as $key => $template_file_object) {
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for tugboat_preview_create_form.
 */
function borg_tugboat_form_tugboat_preview_create_form_alter(&$form, &$form_state, $form_id) {
  // Add extra classes.
  $form['#attributes'] = array('class' => array('borg-tugboat-create-demo-form'));
  $form['create_preview_site']['#attributes'] = array('class' => array('button', 'button-large', 'demo'));
}

/**
 * Implements template_preprocess_HOOK() for tugboat_preview_ready_page.
 *
 * Get the login URL from the preview log.
 */
function borg_tugboat_preprocess_tugboat_preview_ready_page(&$variables) {
  $variables['login_url'] = $variables['url'];
  $log = tugboat_api_curl('/previews/' . $variables['preview_id'] . '/log');

  if ($log['code'] >= 400) {
    backdrop_set_message(t('An error occurred: @message', array('@message' => $log['body']['message'])), 'error');
  }
  else {
    // Since the login URL is towards the end, reverse the array to find it
    // quicker.
    $logs = array_reverse($log['body']);

    foreach ($logs as $l) {
      if (strpos($l['message'], 'Login URL:') === 0) {
        $message = explode(':', $l['message'], 2);
        $variables['login_url'] .= trim($message[1]);
        break;
      }
    }
  }
}
