<?php
/**
 * @file
 * Install and uninstall schema and functions for the xmlsitemap_node module.
 */

/**
 * Implements hook_uninstall().
 */
function xmlsitemap_node_uninstall() {
  backdrop_load('module', 'node');
  backdrop_load('module', 'xmlsitemap');
  $node_types = array_keys(node_type_get_names());
  foreach ($node_types as $node_type) {
    xmlsitemap_link_bundle_delete('node', $node_type);
  }
}
