<?php
/**
 * @file
 * Removes cruft from forms.
 */

/**
 * Implements hook_menu_alter().
 *
 * Removes tabs from the log in and password pages.
 */
function borg_cleanup_menu_alter(&$items) {
  $items['user/login']['type'] = MENU_CALLBACK;
  $items['user/pasword']['type'] = MENU_CALLBACK;
}

/**
 * Implements hook_admin_paths_alter().
 */
function borg_cleanup_admin_paths_alter(&$paths) {
  // Treat user edit pages as non-administrative.
  $paths['user/*/edit'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Removes useless description text from log in form, adds additional links.
 */
function borg_cleanup_form_user_login_alter(&$form, &$form_state) {
  $form['actions']['forgot'] = array(
    '#markup' => '<small>' . l(t('Forgot password?'), 'user/password') . '</small>',
    '#weight' => 10,
  );
  $form['actions']['register'] = array(
    '#markup' => '<small>' . l(t('Create a new account!'), 'user/register') . '</small>',
    '#weight' => 11,
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Removes useless description text.
 */
function borg_cleanup_form_user_register_form_alter(&$form, &$form_state) {
  $form['account']['mail']['#description'] = t('This e-mail address is not made public and will only be used if you request to receive a new password.');
  unset($form['account']['pass']['#description']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Removes useless description text.
 */
function borg_cleanup_form_user_profile_form_alter(&$form, &$form_state) {
  unset($form['account']['pass']['#description']);
  $form['account']['mail']['#description'] = str_replace('A valid e-mail address. All e-mails from the system will be sent to this address. ', '', $form['account']['mail']['#description']);
  $form['account']['mail']['#description'] = str_replace(' or wish to receive certain news or notifications by e-mail', '', $form['account']['mail']['#description']);
}
