<?php
/**
 * @file
 * Project module customizations for BackdropCMS.org
 */

/**
 * Implements hook_project_release_release_xml_alter().
 */
function borg_project_project_release_release_xml_alter(&$release_xml, $release_node, $project_node) {
  // Project release module specifies a "security_update" key such as this:
  //
  // <security_update>true</security_update>
  //
  // But update module still checks for a taxonomy term (legacy from
  // drupal.org). Of the structure:
  //
  // <terms>
  //   <term>
  //     <name>Release type</name>
  //     <value>Security update</value>
  //   </term>
  // </terms>
  //
  // Provide a backwards-compatible key for update module until its key is
  // updated to use the new security_update value directly.
  if ($release_xml['value']['security_update'] === 'true') {
    $release_xml['value']['terms']['term'] = array(
      'name' => 'Release type',
      'value' => 'Security update',
    );
  }
}
