<?php
/**
 * @file
 * Enables Backdrop to send e-mail directly to an SMTP server.
 *
 * This module uses a customized extract of the PHPMailer
 * library (originally by Brent R. Matzelle, now maintained
 *  by Codeworx Tech.) relicensed from LGPL to GPL, included
 * as a part of the module.
 *
 * Overriding mail handling in Backdrop to make SMTP the default
 * transport layer, requires to change the mail_system variable's
 * default value array('default-system' => 'DefaultMailSystem').
 * This module uses array('default-system' => 'SmtpMailSystem').
 */

/**
 * Implements hook_config_info().
 */
function smtp_config_info() {
  $prefixes['smtp.settings'] = array(
    'label' => t('SMTP settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_autoload_info().
 */
function smtp_autoload_info() {
  return array(
    'SmtpMailSystem' => 'includes/smtp.mail.inc',
    'PHPMailer' => 'includes/smtp.phpmailer.inc',
    'SMTP' => 'includes/smtp.transport.inc',
  );
}


/**
 * Implements hook_menu().
 */
function smtp_menu() {
  $items['admin/config/system/smtp'] = array(
    'title'            => 'SMTP Authentication',
    'page callback'    => 'backdrop_get_form',
    'page arguments'   => array('smtp_admin_settings'),
    'access arguments' => array('administer smtp module'),
    'description'      => 'Allow for site emails to be sent through an SMTP server of your choice.',
    'file'             => 'smtp.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function smtp_permission() {
  return array(
    'administer smtp module' => array(
      'title' => t('Administer SMTP Authentication'),
      'description' => t('Perform administration tasks for SMTP Authentication module.'))
  );
}


/**
 * Implements hook_mail().
 */
function smtp_mail($key, &$message, $params) {
  if ($key == 'smtp-test') {
    $message['subject'] = $params['subject'];
    $message['body'] = $params['body'];
  }
}

/**
 * Implementation of hook_cron_queue_info().
 */
function smtp_cron_queue_info() {
  $queues['smtp_send_queue'] = array(
    'worker callback' => 'smtp_send_queue_runner',
    'time' => 60, // This is the max run time per cron run in seconds.
  );
  return $queues;
}

/**
 * smtp_send_queue queuer.
 */
function smtp_send_queue($mailerObj) {
  $queue = BackdropQueue::get('smtp_send_queue');
  $queue->createItem($mailerObj);
}

function smtp_send_queue_runner($variables) {
  _smtp_mailer_send($variables);
}

function _smtp_mailer_send($variables) {
  $mailer = $variables['mailer'];
  $to = $variables['to'];
  $from = $variables['from'];

  // Let the people know what is going on.
  watchdog('smtp', 'Sending mail to: @to', array('@to' => $to));

  // Try to send e-mail. If it fails, set watchdog entry.
  if (!$mailer->Send()) {
    watchdog('smtp', 'Error sending e-mail from @from to @to : !error_message', array('@from' => $from, '@to' => $to, '!error_message' => $mailer->ErrorInfo), WATCHDOG_ERROR);
    return FALSE;
  }

  $mailer->SmtpClose();
  return TRUE;
}
