<?php
/**
 * @file
 * Provides custom blocks for Backdropcms.org
 */

/**
 * Implements hook_block_info().
 */
function borg_blocks_block_info() {
  $blocks['branding'] = array(
    'info' => t('Branding'),
    'description' => t('Backdrop CMS logomark and wordmark.'),
  );
  $blocks['tagline'] = array(
    'info' => t('Tagline & Download'),
    'description' => t('Tagline and download'),
  );
  $blocks['greeting'] = array(
    'info' => t('Greeting'),
    'description' => t('Backdrop CMS greeting block.'),
  );
  $blocks['upgrade'] = array(
    'info' => t('Upgrade info'),
    'description' => t('Information on upgrades from D7.'),
  );
  $blocks['handbook'] = array(
    'info' => t('Handbook Menu'),
    'description' => t('Backdrop CMS Handbook menu, with section titles.'),
  );
  $blocks['rss'] = array(
    'info' => t('Project RSS feed'),
    'description' => t('RSS feed for Backdrop CMS modules, themes, and layouts.'),
  );

  return $blocks;
}

/**
 * Implements function hook_block_view().
 */
function borg_blocks_block_view($delta = '', $settings = array(), $contexts = array()) {
  $block = array();

  switch ($delta) {
    case 'branding':
      $options = array('attributes' => array('class' => array('site-name')));
      $output = l(t('backdrop'), '', $options);

      $uri = backdrop_get_path('module', 'borg_blocks') . '/images/logo.png';
      $image = theme('image', array('uri' => $uri, 'alt' => t('Backdrop CMS Logo')));
      $options = array('html' => TRUE, 'attributes' => array('class' => array('logo'), 'title' => t('Backdrop CMS Home')));
      $output .= l($image, '', $options);

      $block['subject'] = NULL;
      $block['content'] = $output;
      break;

    case 'tagline':
      $block['subject'] = NULL;
      $block['content'] = borg_blocks_tagline($settings);
      break;

    case 'greeting':
      global $user;

      $block['subject'] = NULL;
      if ($user->uid) {
        $block['content'] = t('Hi !name!', array('!name'  => theme('username', array('account' => $user))));
      }
      break;

    case 'upgrade':

      $block['subject'] = t('Upgrade from Drupal 7');
      $block['content'] = borg_blocks_upgrade($settings);
      break;

    case 'handbook':
      $tree = menu_tree('menu-handbook');

      $block['subject'] = NULL;
      $block['content'] = backdrop_render($tree);
      break;

    case 'rss':
      $block['subject'] = NULL;
      $block['content'] = backdrop_get_feeds();
      break;
  }

  return $block;
}

function borg_blocks_tagline($settings) {
  $version = check_plain($settings['version']);

  $demo_attributes = array('class' => array('button', 'demo'));
  if (module_exists('borg_tugboat')) {
    $demo_text = t('Demo Backdrop');
    $demo_link = l($demo_text, 'demo/create', array('attributes' => $demo_attributes, 'html' => TRUE));
  }
  else {
    $pantheon_url = 'https://dashboard.pantheon.io/sites/create?upstream_id=bf703821-4c18-45a1-88b8-3d9ec302273d';
    $demo_text = t('Backdrop on Pantheon');
    $demo_link = l($demo_text, $pantheon_url, array('attributes' => $demo_attributes, 'html' => TRUE));
  }

  $dl_url = 'https://github.com/backdrop/backdrop/releases/download/' . $version . '/backdrop.zip';
  $dl_text = t('Download Backdrop');
  $dl_attributes = array('class' => array('button', 'download'));
  $download_link = l($dl_text, $dl_url, array('attributes' => $dl_attributes, 'html' => TRUE));

  //$output  = '<h1 class="page-title">Backdrop CMS</h1>';
  $output  = '<h2>The free and Open Source CMS<br/>';
  $output .= '<span>that helps you build websites for businesses and non-profits.</span></h2>';

  $output .= '<div class="tagline-section section-demo">';
  $output .=   $demo_link . '<span class="version">v' . $version . '</span>';
  $output .= '  <p class="subtext">';
  $output .=      l(t('other ways to try'), 'try-backdrop');
  $output .= '  </p>';
  $output .= '</div>';


  $requirements = l(t('requirements'), 'requirements');
  $installing = l(t('installing'), 'installation');
  $upgrading = l(t('upgrading'), 'upgrade');

  $output .= '<div class="tagline-section section-download">';
  $output .= $download_link  . '<span class="version">v' . $version . '</span>';
  $output .= '  <p class="subtext">';
  $output .=      $requirements . ' / ' . $installing . ' / ' . $upgrading;
  $output .= '  </p>';
  $output .= '</div>';

  return $output;
}

function borg_blocks_upgrade($settings) {
  $path = backdrop_get_path('module', 'borg_blocks');
  $button = l(t('Upgrade from Drupal'), 'https://backdropcms.org/upgrade-from-drupal', array('attributes' => array('class' => array('button'))));

  $included_modules = l(t('60+ included modules'), 'node/1683');
  $included_modules_icon = '<img src="/' . $path . '/images/gift--white--256.png" />';
  $included_modules_icon_link = l($included_modules_icon, 'node/1683', array('html' => TRUE, 'attributes' => array('class' => array('icon'))));

  $top_modules = l(t('91% of top modules ready'), 'node/2255');
  $top_modules_icon = '<img src="/' . $path . '/images/check-circle--white--256.png" />';
  $top_modules_icon_link = l($top_modules_icon, 'node/2255', array('html' => TRUE, 'attributes' => array('class' => array('icon'))));

  $total_addons = l(t('500+ total add-ons'), 'node/1686');
  $total_addons_icon = '<img src="/' . $path . '/images/puzzle-piece--white--256.png" />';
  $total_addons_icon_link = l($total_addons_icon, 'node/1686', array('html' => TRUE, 'attributes' => array('class' => array('icon'))));

  $output  = '<div class="container container-fluid">';
  $output .= '  <div class="row">';
  $output .= '    <div class="col-md-4 column">';
  $output .=        $included_modules_icon_link;
  $output .= '      <h3>' . $included_modules . '</h3>';
  $output .= '      <p>' . t('More than than 60 Drupal modules have been merged into Backdrop core.') . '</p>';
  $output .= '    </div>';
  $output .= '    <div class="col-md-4 column">';
  $output .=        $top_modules_icon_link;
  $output .= '      <h3>' . $top_modules . '</h3>';
  $output .= '      <p>' . t('Of the top 100 Drupal 7 modules, 91 of them are ready for Backdrop CMS.') . '</p>';
  $output .= '    </div>';
  $output .= '    <div class="col-md-4 column">';
  $output .=        $total_addons_icon_link;
  $output .= '      <h3>' . $total_addons . '</h3>';
  $output .= '      <p>' . t('More than 500 modules, themes, and layouts are available for Backdrop CMS.') . '</p>';
  $output .= '    </div>';
  $output .= '  </div>';
  $output .= '</div>';
  $output .= '<div class="upgrade-cta">';
  $output .= '  <div class="container container-fluid">';
  $output .= '    <p>' . t('Find out what\'s involved in upgrading your Drupal 7 site, today. &nbsp;') . $button . '</p>';
  $output .= '  </div>';
  $output .= '</div>';

  return $output;
}

/**
 * Implements function hook_block_configure().
 */
function borg_blocks_block_configure($delta = '', $settings = array()) {
  $form = array();

  if ($delta == 'tagline') {
    $settings += array(
      'version' => '1.13.0',
    );

    $form['version'] = array(
      '#type' => 'textfield',
      '#size' => 10,
      '#title' => t('Current Version Number'),
      '#default_value' => $settings['version'],
    );

  }

  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * In https://github.com/backdrop/backdrop/commit/8977e8e8b191a2c7323d555ca486c248a0b55af0
 * we added the autofocus to the title of node and taxonomy add forms, but on the
 * front end when a node form is embeded in a block below the fold this is
 * undesirable; causing the page load to scroll down to that form element. In
 * this case the backdropcms.org homepage.
 */
function borg_blocks_form_supporter_node_form_alter(&$form, &$form_state, $form_id) {
  // Only unset for homepage.
  if (current_path() == 'node/19') {
    unset($form['title']['#attributes']['autofocus']);
    $form['actions']['submit']['#value'] = t('Submit');
  }
}
