<?php
/**
 * @file
 * Provides custom blocks for Backdropcms.org
 */

/**
 * Implements hook_block_info().
 */
function borg_blocks_block_info() {
  // New home page blocks
  $blocks['resources'] = array(
    'info' => t('Get Started with Backdrop'),
    'description' => t('Home page: Resources section'),
  );
  $blocks['community'] = array(
    'info' => t('Join the community'),
    'description' => t('Home page: Community section'),
  );

  $blocks['branding'] = array(
    'info' => t('Branding'),
    'description' => t('Backdrop CMS logomark and wordmark.'),
  );
  $blocks['tagline'] = array(
    'info' => t('Tagline & Download'),
    'description' => t('Tagline and download'),
  );
  $blocks['audiences'] = array(
    'info' => t('Backdrop for Audiences'),
    'description' => t('Homepage block'),
  );
  $blocks['greeting'] = array(
    'info' => t('Greeting'),
    'description' => t('Backdrop CMS greeting block.'),
  );
  $blocks['upgrade'] = array(
    'info' => t('Upgrade info'),
    'description' => t('Information on upgrades from D7.'),
  );
  $blocks['handbook'] = array(
    'info' => t('Handbook Menu'),
    'description' => t('Backdrop CMS Handbook menu, with section titles.'),
  );
  $blocks['rss'] = array(
    'info' => t('Project RSS feed'),
    'description' => t('RSS feed for Backdrop CMS modules, themes, and layouts.'),
  );

  return $blocks;
}

/**
 * Implements function hook_block_view().
 */
function borg_blocks_block_view($delta = '', $settings = array(), $contexts = array()) {
  $block = array();

  switch ($delta) {
    case 'resources':
      $block_title = '<div class="visual-tag">Resources</div>';
      $block_title .= '<div class="b-resources__title">Get Started with Backdrop</div>';

      $copy = t('Our documentation is written and maintained for people, by people, just like our code.');

      $resource_links = array(
        'api' => array(
          'url' => 'https://api.backdropcms.org',
          'name' => t('Documentation & API'),
          'more' => t('Find complete documentation for people who are using Backdrop CMS.'),
        ),
        'forum' => array(
          'url' => 'https://forum.backdropcms.org',
          'name' => t('Visit the Backdrop Forum'),
          'more' => t('Visit our forum with questions. All answers will be provided with dignity and respect.'),
        ),
        'hours' => array(
          'url' => '/support/meetings',
          'name' => t('Join Office Hours'),
          'more' => t('Visit our virtual office hours every Wednesday from 12-2 pm EST'),
        ),
      );
      $items = array();
      foreach ($resource_links as $resource) {
        $link_content = '<div class="b-resources__resource-name">' . $resource['name'] . '</div>';
        $link_content .= $resource['more'];
        $items[] = l($link_content, $resource['url'], array('html' => TRUE));
      }
      $attributes = array('class' => array('b-resources__links'));
      $resources = theme('item_list', array('items' => $items, 'attributes' => $attributes));

      $block['subject'] = $block_title;
      $block['content'] = array(
        'copy' => $copy,
        'resources' => $resources,
      );
      break;

    case 'community':
      $block_title = '<div class="visual-tag">Get Involved</div>';
      $block_title .= '<div class="b-community__title">Join the community</div>';

      $copy = t('Whether you’re a developer, designer, or enthusiast, your contributions make Backdrop better for everyone. Join a vibrant open source community.');

      $button_attributes = array(
        'class' => array('borg__button', 'borg__button--primary', 'borg__button--right-arrow'));
      $options = array('attributes' => $button_attributes);
      $button = l(t('Join the conversation'), 'https://forum.backdropcms.org', $options);

      $image_path = backdrop_get_path('module', 'borg_blocks') . '/images/';
      $photo_files = array(
        'Backdrop-BDay-Nantes.jpg',
        'Backdrop-BDay-Oakland.jpg',
        'Justin-Laryn.jpg',
        'migrating-backdrop-on-pantheon.jpg',
        'tcbackdrop.jpg',
      );
      $items = array();
      foreach ($photo_files as $filename) {
        $items[] = theme('image', array('path' => $image_path . $filename));
      }
      $attributes = array('class' => array('b-community__photos'));
      $photos = theme('item_list', array('items' => $items, 'attributes' => $attributes));

      $block['subject'] = $block_title;
      $block['content'] = array(
        'copy' => $copy,
        'photos' => $photos,
        'button' => $button,
      );
      break;

    case 'branding':
      $options = array('attributes' => array('class' => array('site-name')));
      $output = l(t('backdrop'), '', $options);

      $uri = backdrop_get_path('module', 'borg_blocks') . '/images/logo.png';
      $image = theme('image', array('uri' => $uri, 'alt' => t('Backdrop CMS Logo')));
      $options = array('html' => TRUE, 'attributes' => array('class' => array('logo'), 'title' => t('Backdrop CMS Home')));
      $output .= l($image, '', $options);

      $block['subject'] = NULL;
      $block['content'] = $output;
      break;

    case 'tagline':
      $block['subject'] = NULL;
      $block['content'] = borg_blocks_tagline($settings);
      break;

    case 'greeting':
      global $user;

      $block['subject'] = NULL;
      if ($user->uid) {
        $block['content'] = t('Hi !name!', array('!name'  => theme('username', array('account' => $user))));
      }
      break;

    case 'audiences':
      $block['subject'] = NULL;
      $block['content'] = borg_blocks_audiences($settings);
      break;

    case 'upgrade':

      $block['subject'] = t('Upgrade from Drupal 7');
      $block['content'] = borg_blocks_upgrade($settings);
      break;

    case 'handbook':
      $tree = menu_tree('menu-handbook');

      $block['subject'] = NULL;
      $block['content'] = backdrop_render($tree);
      break;

    case 'rss':
      $block['subject'] = NULL;
      $block['content'] = backdrop_get_feeds();
      break;
  }

  return $block;
}

function borg_blocks_tagline($settings) {
  $version = check_plain($settings['version']);

  $button_class_name = 'borg__button';
  if (module_exists('tugboat')) {
    $demo_text = t('Demo Backdrop CMS');
    $demo_link = l($demo_text, 'demo',
      array(
        'attributes' => array(
          'class' => array(
            $button_class_name,
            $button_class_name . '--primary',
          )
        ),
        'html' => TRUE,
      )
    );
  }
  else {
    $pantheon_url = 'https://dashboard.pantheon.io/sites/create?upstream_id=bf703821-4c18-45a1-88b8-3d9ec302273d';
    $demo_text = t('Backdrop on Pantheon');
    $demo_link = l($demo_text, $pantheon_url,
      array(
        'attributes' => array(
          'class' => array(
            $button_class_name,
            $button_class_name . '--primary',
          )
        ),
        'html' => TRUE,
      )
    );

  }

  $dl_url = 'https://github.com/backdrop/backdrop/releases/download/' . $version . '/backdrop.zip';
  $dl_text = t('Download Backdrop&nbsp;CMS') . ' <span class="version">v&nbsp;' . $version . '</span>';

  $download_link = l($dl_text, $dl_url,
    array(
      'attributes' => array(
        'class' => array(
          $button_class_name,
          $button_class_name . '--secondary',
        )
      ),
      'html' => TRUE,
    )
  );

  $output  =
    '<h1 class="tagline-block__headline-wrapper">' .
      '<span class="tagline-block__primary-text">'. t('Put your content center stage') . '</span>' .
    '</h1>' .
    '<p>' .
      t('Backdrop CMS is a free and Open Source Content Management System that helps you build modern, comprehensive websites on a reasonable budget.') .
    '</p>';

  $output .= '<ul class="tagline-block__ctas">';
  $output .=   '<li>' . $demo_link . '</li>';
  $output .=   '<li>' . $download_link . '</li>';
  $output .= '</ul>';

  return $output;
}

function borg_blocks_audiences($settings) {
  $button_class_name = 'borg__button';

  $output =
    '<span class="audiences-block__visual-tag visual-tag">'.
      t('Sites Showcase') .
    '</span> ' .
    '<h2 class="audiences-block__title">' .
      t('A flexible CMS for any person or organization') .
    '</h2>' .
    '<div class="audiences-block__body">' .
        t('A flexible CMS for any person or organization') .
      '<p>' .
        t('Backdrop CMS is being used across more than 3,600+ sites for both individuals and organization of all kinds.') .
      '</p>' .
      l(
        t('See the Showcase'),
        'showcase',
        array(
          'attributes' => array(
            'class' => array(
              $button_class_name,
              $button_class_name . '--primary',
              $button_class_name . '--right-arrow',
            )
          ),
        )
      ) .
    '</div>';

  $output .= '<ul class="audiences-block__organizations chonky-link-bar__outer-wrapper">';
  $audiences_menu = menu_load_links('menu-cms-audiences');
  foreach ($audiences_menu as $key => $audiences_menu_item) {
    if (!empty($audiences_menu_item['hidden'])) {
      break;
    }
    $mlid = $audiences_menu_item['mlid'];

    $options = $audiences_menu_item['options'];
    $options['attributes']['class'][] = 'audiences-block__organization-link';
    $options['attributes']['class'][] = 'audiences-block__organization-link--' . $mlid;
    $options['attributes']['class'][] = 'chonky-link-bar';

    $output .=
      '<li class="audiences-block__organization-item chonky-link-bar__item">' .
        l($audiences_menu_item['link_title'], $audiences_menu_item['link_path'], $options) .
      '</li>';
  }

  $output .= '</ul>';

  return $output;
}

function borg_blocks_upgrade($settings) {
  // Included in core
  $modules_core = 75;
  // Percent ready
  $modules_top = 97;
  // Number of modules
  $projects_available = 1100;

  $path = backdrop_get_path('module', 'borg_blocks');
  $button = l(t('Upgrade from Drupal'), 'node/4967', array('attributes' => array('class' => array('button'))));

  $included_modules = l(t("$modules_core+ included modules"), 'https://docs.backdropcms.org/documentation/features-added-to-core');
  $included_modules_icon = '<img src="/' . $path . '/images/gift--white--256.png" />';
  $included_modules_icon_link = l($included_modules_icon, 'https://docs.backdropcms.org/documentation/features-added-to-core', array('html' => TRUE, 'attributes' => array('class' => array('icon'))));

  $top_modules = l(t("$modules_top% of top modules"), 'https://docs.backdropcms.org/documentation/top-100-drupal-7-modules');
  $top_modules_icon = '<img src="/' . $path . '/images/check-circle--white--256.png" />';
  $top_modules_icon_link = l($top_modules_icon, 'https://docs.backdropcms.org/documentation/top-100-drupal-7-modules', array('html' => TRUE, 'attributes' => array('class' => array('icon'))));

  $total_addons = l(t("$projects_available+ total add-ons"), 'node/1686');
  $total_addons_icon = '<img src="/' . $path . '/images/puzzle-piece--white--256.png" />';
  $total_addons_icon_link = l($total_addons_icon, 'node/1686', array('html' => TRUE, 'attributes' => array('class' => array('icon'))));

  $output  = '<div class="container container-fluid">';
  $output .= '  <div class="row">';
  $output .= '    <div class="col-md-4 column">';
  $output .=        $included_modules_icon_link;
  $output .= '      <h3>' . $included_modules . '</h3>';
  $output .= '      <p>' . t("More than $modules_core Drupal modules have been merged into Backdrop core.") . '</p>';
  $output .= '    </div>';
  $output .= '    <div class="col-md-4 column">';
  $output .=        $top_modules_icon_link;
  $output .= '      <h3>' . $top_modules . '</h3>';
  $output .= '      <p>' . t("Of the top 100 Drupal 7 modules, $modules_top of them are ready for Backdrop CMS.") . '</p>';
  $output .= '    </div>';
  $output .= '    <div class="col-md-4 column">';
  $output .=        $total_addons_icon_link;
  $output .= '      <h3>' . $total_addons . '</h3>';
  $output .= '      <p>' . t("More than $projects_available modules, themes, and layouts are available for use today.") . '</p>';
  $output .= '    </div>';
  $output .= '  </div>';
  $output .= '</div>';
  $output .= '<div class="upgrade-cta">';
  $output .= '  <div class="container container-fluid">';
  $output .= '    <p>' . t('Find out what\'s involved in upgrading your Drupal 7 site, today. &nbsp;') . $button . '</p>';
  $output .= '  </div>';
  $output .= '</div>';

  return $output;
}

/**
 * Implements function hook_block_configure().
 */
function borg_blocks_block_configure($delta = '', $settings = array()) {
  $form = array();

  if ($delta == 'tagline') {
    $settings += array(
      'version' => '1.13.0',
    );

    $form['version'] = array(
      '#type' => 'textfield',
      '#size' => 10,
      '#title' => t('Current Version Number'),
      '#default_value' => $settings['version'],
    );

  }

  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * In https://github.com/backdrop/backdrop/commit/8977e8e8b191a2c7323d555ca486c248a0b55af0
 * we added the autofocus to the title of node and taxonomy add forms, but on the
 * front end when a node form is embeded in a block below the fold this is
 * undesirable; causing the page load to scroll down to that form element. In
 * this case the backdropcms.org homepage.
 */
function borg_blocks_form_supporter_node_form_alter(&$form, &$form_state, $form_id) {
  // Only unset for homepage.
  if (current_path() == 'node/19') {
    unset($form['title']['#attributes']['autofocus']);
    $form['actions']['submit']['#value'] = t('Submit');
  }
}

/**
 * Prepare variables for Block templates.
 *
 * @see block--borg-blocks--resources.tpl.php
 * @see block--borg-blocks--community.tpl.php
 */
function borg_blocks_preprocess_block(&$variables){
  if ($variables['block']->module == 'borg_blocks') {
    if ($variables['block']->delta == 'community') {
      $variables['copy'] = $variables['content']['copy'];
      $variables['photos'] = $variables['content']['photos'];
      $variables['button'] = $variables['content']['button'];
    }
    elseif ($variables['block']->delta == 'resources') {
      $variables['copy'] = $variables['content']['copy'];
      $variables['resources'] = $variables['content']['resources'];
    }
  }
}
