<?php
/**
 * @file
 * Adds keyword-rich metatags for SEO.
 */

/**
 * Prepares variables for page templates.
 */
function borg_metadata_preprocess_page(&$variables) {
  if ($variables['is_front']) {
    // Add home page header tag
    //$variables['head_title'] = t('Backdrop CMS: Freee Open Source Content Management System');

    // Add a description tag.
    $description = array(
      '#type' => 'head_tag',
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'description',
        'content' => t('Backdrop CMS is simple, lightweight, and easy to use. A PHP content management system used to build creative, professional websites.'),
      )
    );
    backdrop_add_html_head($description, 'description');
  }
}
