<?php
/**
 * @file
 * Adds keyword-rich metatags for SEO.
 */

/**
 * Prepares variables for page templates.
 */
function borg_metadata_preprocess_page(&$variables) {
  if ($variables['is_front']) {
    // Add home page header tag
    //$variables['head_title'] = t('Backdrop CMS: Freee Open Source Content Management System');

    // Add a description tag.
    $description = array(
      '#type' => 'head_tag',
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'description',
        'content' => t('Backdrop CMS is a simple, lightweight, and easy to use Content Management System used to build attractive, professional websites.'),
      ),
    );
    backdrop_add_html_head($description, 'description');

    // <!-- Global site tag (gtag.js) - Google Ads: 859540611 -->
    $google_ads_options = array(
      'type' => 'external',
      'scope' => 'header',
      'attributes' => array(
        'async' => 'async',
      ),
    );
    backdrop_add_js('https://www.googletagmanager.com/gtag/js?id=AW-859540611', $google_ads_options);
    $google_ads_inline = "
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('set', 'allow_ad_personalization_signals', false);
  gtag('js', new Date());
  gtag('config', 'AW-859540611');";
    backdrop_add_js($google_ads_inline, 'inline');
  }
}
