<?php
/**
 * @file
 * Functional tests for the XML sitemap engines module.
 */

/**
 * @file
 * Unit tests for the XML sitemap engines project.
 */

/**
 * Implements hook_menu().
 */
function xmlsitemap_engines_test_menu() {
  $items['ping'] = array(
    'page callback' => 'xmlsitemap_engines_test_pinged',
    // @codingStandardsIgnoreLine
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_xmlsitemap_engine_info().
 */
function xmlsitemap_engines_test_xmlsitemap_engine_info() {
  $engines['simpletest'] = array(
    'name' => t('SimpleTest'),
    'url' => 'http://example.com/',
  );
  return $engines;
}

/**
 * Implements hook_xmlsitemap_engine_info_alter().
 */
function xmlsitemap_engines_test_xmlsitemap_engine_info_alter(&$engines) {
  $engines['simpletest']['url'] = url('ping', array(
    'absolute' => TRUE,
    'query' => array('sitemap' => ''),
  )) . '[sitemap]';
}

/**
 * Menu callback. Logs to watchdog on ping.
 */
function xmlsitemap_engines_test_pinged() {
  if (empty($_GET['sitemap']) || !valid_url($_GET['sitemap'])) {
    $message = 'No valid sitemap parameter provided.';
    $variables = array();
    watchdog('xmlsitemap', $message, $variables, WATCHDOG_WARNING);
    backdrop_add_http_header('Status', '404 Not Found');
  }
  else {
    $message = 'Received ping for @sitemap.';
    $variables = array('@sitemap' => $_GET['sitemap']);
    watchdog('xmlsitemap', $message, $variables);
  }
  print format_string($message, $variables);
  backdrop_exit();
}
