<?php
/**
 * @file
 * Provides customizations for Backdropcms.org user profiles.
 */

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form.
 */
function borg_profile_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  // Only edit the form on user profile pages.
  $user = menu_get_object('user', 1);
  if ($user !== NULL) {
    $username = '';

    // Get the user's GitHub username from their GitHub social field (if set).
    if (isset($user->field_social)) {
      $github_url = '';
      foreach ($user->field_social[$user->langcode] as $service) {
        if ($service['service'] == 'github') {
          $github_url = $service['url'];
          break;
        }
      }
      if (!empty($github_url)) {
        $url_parts = explode('/', $github_url);
        $username = array_pop($url_parts);
      }
    }

    // Get the user's BackdropCMS.org username otherwise.
    if (empty($username) && !empty($user->name)) {
      $username = $user->name;
    }

    if (!empty($username)) {
      // Search for projects by username and hide the exposed form.
      $form_state['input']['user'] = $username;
      $form['#attributes']['class'][] = 'element-hidden';
    }
    else {
      // Hide the form when there's no username to search by (otherwise all
      // projects will be displayed).
      $form['#access'] = FALSE;
    }
  }
}
