<?php

/**
 * @file
 * Testing functionality for Akismet module.
 */

/**
 * Implements hook_entity_info().
 */
function akismet_test_entity_info() {
  $info['akismet_test'] = array(
    'label' => 'Akismet test record',
    'bundle label' => t('Type'),
    'controller class' => 'EntityDatabaseStorageController',
    'entity class' => 'AkismetTest',
    'base table' => 'akismet_test',
    'uri callback' => 'akismet_test_uri',
    'entity keys' => array(
      'id' => 'mid',
      'label' => 'title',
    ),
  );
  return $info;
}

/**
 * Implements hook_autoload_info().
 */
function akismet_test_autoload_info() {
  return array(
    'AkismetTest' => 'akismet_test.entity.inc',
  );
}

/**
 * Entity URI callback.
 */
function akismet_test_uri($record) {
  return array(
    'path' => 'akismet-test/form/' . $record->mid,
  );
}

/**
 * Implements hook_menu().
 */
function akismet_test_menu() {
  $items['akismet-test/form'] = array(
    'title' => 'Akismet test form',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('akismet_test_form'),
    'access callback' => TRUE,
  );
  $items['akismet-test/form/%akismet_test/delete'] = array(
    'title' => 'Delete Akismet test item',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('akismet_test_delete_form', 2),
    'access callback' => TRUE,
  );
  $items['akismet-test/form/views/reset'] = array(
    'page callback' => 'akismet_test_views_reset',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['akismet-test/pong'] = array(
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('akismet_test_pong_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_forms().
 */
function akismet_forms() {
  $forms['akismet_basic_test_form'] = array(
    'callback' => 'akismet_test_form',
  );
  return $forms;
}

/**
 * Implements hook_akismet_form_list().
 */
function akismet_test_akismet_form_list() {
  $forms['akismet_test_form'] = array(
    'title' => 'Akismet test form',
    'entity' => 'akismet_test',
    'moderation callback' => 'akismet_test_akismet_form_moderation',
    'delete form' => 'akismet_test_delete_form',
  );
  // The basic test form is identical to the akismet_test_form, but only
  // registers minimal information (e.g., no entity or moderation callback) to
  // integrate with Akismet.
  $forms['akismet_basic_test_form'] = array(
    'title' => 'Akismet basic test form',
  );
  // Same as above, but supports elements for text analysis.
  $forms['akismet_basic_elements_test_form'] = array(
    'title' => 'Akismet basic elements test form',
  );
  // Same as akismet_test_form, but supports an entity delete callback.
  $forms['akismet_entity_test_form'] = array(
    'title' => 'Akismet entity test form',
    'entity' => 'akismet_test',
    'entity delete callback' => 'akismet_test_delete',
  );
  return $forms;
}

/**
 * Implements hook_akismet_form_info().
 */
function akismet_test_akismet_form_info($form_id) {
  if ($form_id == 'akismet_basic_test_form') {
    return array();
  }
  $form_info = array(
    'bypass access' => array('administer akismet'),
    'elements' => array(
      'title' => 'Title',
      'body' => 'Body',
      'exclude' => 'Some other field',
      'parent][child' => 'Nested element',
      'field' => 'Multiple value field',
    ),
    'mapping' => array(
      'post_id' => 'mid',
      'comment_author' => 'name',
    ),
  );
  return $form_info;
}

/**
 * Page callback; Resets the akismet_test_form() [page] view counter.
 */
function akismet_test_views_reset() {
  state_del('akismet_test.form.views');
  cache_clear_all();
  backdrop_goto();
}

/**
 * Form builder for Akismet test form.
 */
function akismet_test_form($form, &$form_state, $mid = NULL) {
  // Due to #limit_validation_errors, submitting the form with the "Add" button
  // will only expose validated values in the submit handler, so our storage may
  // be incomplete. Therefore, the default values always have to be overloaded.
  $form_state += array('storage' => array());
  if (isset($mid) && ($record = akismet_test_load($mid))) {
    $form_state['storage'] = (array) $record;
  }
  $form_state['storage'] += array(
    'mid' => $mid,
    'title' => '',
    'body' => '',
    'exclude' => '',
    'parent' => array('child' => ''),
    'field' => array(),
    'status' => 1,
  );
  // Always add an empty field the user can submit.
  $form_state['storage']['field']['new'] = '';

  // Output a page view counter for page/form cache testing purposes.
  $count = state_get('akismet_test.form.views', 1);
  $reset_link = l('Reset', 'akismet-test/form/views/reset', array('query' => backdrop_get_destination()));
  $form['views'] = array(
    '#markup' => '<p>' . 'Views: ' . $count++ . ' ' . $reset_link . '</p>',
  );
  state_set('akismet_test.form.views', $count);

  // Conditionally enable form caching.
  if (state_get('akismet_test.form.cache', FALSE)) {
    $form_state['cache'] = TRUE;
  }

  $form['#tree'] = TRUE;
  $form['mid'] = array(
    '#type' => 'hidden',
    '#value' => $form_state['storage']['mid'],
  );
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => 'Title',
    '#default_value' => $form_state['storage']['title'],
    '#required' => TRUE,
  );
  $form['body'] = array(
    '#type' => 'textfield',
    '#title' => 'Body',
    '#default_value' => $form_state['storage']['body'],
  );
  $form['exclude'] = array(
    '#type' => 'textfield',
    '#title' => 'Some other field',
    '#default_value' => $form_state['storage']['exclude'],
  );
  $form['parent']['child'] = array(
    '#type' => 'textfield',
    '#title' => 'Nested element',
    '#default_value' => $form_state['storage']['parent']['child'],
  );

  $form['field'] = array(
    '#type' => 'fieldset',
    '#title' => 'Field',
  );
  $weight = 0;
  foreach ($form_state['storage']['field'] as $delta => $value) {
    $form['field'][$delta] = array(
      '#type' => 'textfield',
      '#title' => 'Field ' . $delta,
      '#default_value' => $value,
      '#weight' => $weight++,
    );
  }
  $form['field']['new']['#weight'] = 999;
  $form['field']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Add',
    '#limit_validation_errors' => array(array('field')),
    '#submit' => array('akismet_test_form_field_submit'),
    '#weight' => 1000,
  );

  $form['status'] = array(
    '#type' => 'checkbox',
    '#title' => 'Published',
    '#default_value' => $form_state['storage']['status'],
    // For simplicity, re-use Akismet module's administration permission.
    '#access' => user_access('administer akismet'),
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => 'Submit');

  return $form;
}

/**
 * Form element submit handler for akismet_test_form().
 */
function akismet_test_form_field_submit($form, &$form_state) {
  // Remove internal Form API values.
  form_state_values_clean($form_state);
  // Remove all empty values of the multiple value field.
  $form_state['values']['field'] = array_filter($form_state['values']['field']);
  // Update the storage with submitted values.
  $form_state['storage'] = $form_state['values'];
  // Store the new value and clear out the 'new' field.
  if (isset($form_state['values']['field']['new'])) {
    $form_state['storage']['field'][] = $form_state['values']['field']['new'];
  }
  unset($form_state['input']['field']['new']);

  $form_state['rebuild'] = TRUE;
}

/**
 * Form submit handler for akismet_test_form().
 */
function akismet_test_form_submit($form, &$form_state) {
  $form_state['values']['field'][] = $form_state['values']['field']['new'];
  unset($form_state['values']['field']['new']);

  // Store submission.
  form_state_values_clean($form_state);
  //$record = (object) $form_state['values'];
  $record = entity_create('akismet_test', $form_state['values']);
  $record->save();
  //akismet_test_save($record);
  $form_state['values']['mid'] = $record->mid;

  // Redirect to stored entry.
  $form_state['redirect'] = 'akismet-test/form/' . $record->mid;

  backdrop_set_message('Successful form submission.');
  backdrop_set_message('<pre>' . var_export($record, TRUE) . '</pre>');
}

/**
 * Akismet form moderation callback for an akismet_test record.
 */
function akismet_test_akismet_form_moderation(&$form, &$form_state) {
  $form_state['values']['status'] = 0;
}

/**
 * Loads a {akismet_test} data record by id.
 */
function akismet_test_load($mid) {
  return db_query('SELECT * FROM {akismet_test} WHERE mid = :mid', array(':mid' => $mid))->fetch();
}

/**
 * Saves an {akismet_test} data record.
 */
function akismet_test_save($record) {
  // Load the stored entity, if any.
  if (!empty($record->mid) && !isset($record->original)) {
    $record->original = entity_load_unchanged('akismet_test', $record->mid);
  }

  $update = !empty($record->mid) ? array('mid') : array();
  $status = backdrop_write_record('akismet_test', $record, $update);
  if ($status === SAVED_NEW) {
    module_invoke_all('akismet_test_insert', $record);
    module_invoke_all('entity_insert', $record, 'akismet_test');
  }
  else {
    $status = SAVED_UPDATED;
    module_invoke_all('akismet_test_update', $record);
    module_invoke_all('entity_update', $record, 'akismet_test');
  }
  return $status;
}

/**
 * Deletes a {akismet_test} data record.
 *
 * @param int $mid
 *   The mid to delete.
 */
function akismet_test_delete($mid) {
  $record = akismet_test_load($mid);
  if ($record) {
    module_invoke_all('entity_delete', $record, 'akismet_test');
  }
  db_delete('akismet_test')
    ->condition('mid', $mid)
    ->execute();
}

/**
 * Form constructor for deleting a Akismet test item.
 */
function akismet_test_delete_form($form, &$form_state, $record) {
  $form['mid'] = array('#type' => 'value', '#value' => $record->mid);
  return confirm_form($form,
    t('Are you sure you want to delete the %title?', array('%title' => $record->title)),
    'akismet-test/form/' . $record->mid,
    NULL,
    t('Delete')
  );
}

/**
 * Form submission handler for akismet_test_delete_form().
 */
function akismet_test_delete_form_submit($form, &$form_state) {
  akismet_test_delete($form_state['values']['mid']);
  backdrop_set_message('The record has been deleted.');
  $form_state['redirect'] = 'akismet-test/form';
}

/**
 * Provides a form to test the akismet pong callback.  The callback must be
 * called as a POST request and so just using a straight-forward test directly
 * fails as these are all GET requests.
 */
function akismet_test_pong_form($form, &$form_state) {
  $form['#action'] = url("akismet/pong");
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}
