name: ddev-borg
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        labels:
            com.ddev.platform: ddev
        name: ddev-borg_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.4:v1.24.4
                gid: "20"
                uid: "501"
                username: jlampton
            context: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-borg-db
        environment:
            BITNAMI_VOLUME_DIR: ""
            COLUMNS: "131"
            DDEV_DATABASE: mariadb:10.4
            DDEV_DATABASE_FAMILY: mysql
            DDEV_GOARCH: arm64
            DDEV_GOOS: darwin
            DDEV_HOSTNAME: borg.ddev.site
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: https://borg.ddev.site
            DDEV_PROJECT: borg
            DDEV_PROJECT_TYPE: backdrop
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: borg
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "42"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/borg-db/mysql_history
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: America/Los_Angeles
            USER: jlampton
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: borg-db
        image: ddev/ddev-dbserver-mariadb-10.4:v1.24.4-borg-built
        labels:
            com.ddev.app-type: backdrop
            com.ddev.approot: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo
            com.ddev.platform: ddev
            com.ddev.site-name: borg
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "52547"
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: "501:20"
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/jlampton
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:v1.24.4
                DDEV_DATABASE: mariadb:10.4
                DDEV_PHP_VERSION: "8.3"
                gid: "20"
                uid: "501"
                username: jlampton
            context: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-borg-web
        environment:
            COLUMNS: "131"
            COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
            COREPACK_HOME: /mnt/ddev-global-cache/corepack
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.4
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: www
            DDEV_FILES_DIR: /var/www/html/www/files
            DDEV_FILES_DIRS: /var/www/html/www/files
            DDEV_GOARCH: arm64
            DDEV_GOOS: darwin
            DDEV_HOSTNAME: borg.ddev.site
            DDEV_MUTAGEN_ENABLED: "true"
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: https://borg.ddev.site
            DDEV_PROJECT: borg
            DDEV_PROJECT_TYPE: backdrop
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: borg
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.24.4
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DDEV_XHPROF_MODE: prepend
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: www
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "42"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/borg-web/mysql_history
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=borg.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            START_SCRIPT_TIMEOUT: "30"
            TERMINUS_MACHINE_TOKEN: nMaZxGbTb_I-bzKDfnfHbLFZUQkjn4Db-mFcfoMn1xZ9H
            TZ: America/Los_Angeles
            USER: jlampton
            VIRTUAL_HOST: borg.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:borg.ddev.site
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: borg-web
        image: ddev/ddev-webserver:v1.24.4-borg-built
        labels:
            com.ddev.app-type: backdrop
            com.ddev.approot: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo
            com.ddev.platform: ddev
            com.ddev.site-name: borg
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "52549"
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "52548"
              target: 443
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 8025
        restart: "no"
        user: "501:20"
        volumes:
            - source: project_mutagen
              target: /var/www
              type: volume
              volume:
                nocopy: true
            - source: project_mutagen
              target: /tmp/project_mutagen
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              read_only: true
              source: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - bind:
                create_host_path: true
              source: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/www/files
              target: /var/www/html/www/files
              type: bind
            - bind:
                create_host_path: true
              source: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo/.git
              target: /var/www/html/.git
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
            - bind:
                create_host_path: true
              source: /Users/jlampton/Sites/_backdrop/_contributions
              target: /Users/jlampton/Sites/_backdrop/_contributions
              type: bind
        working_dir: /var/www/html/www
    xhgui:
        container_name: ddev-borg-xhgui
        depends_on:
            db:
                condition: service_started
                required: true
        environment:
            DDEV_DATABASE_FAMILY: mysql
            HTTP_EXPOSE: 8143:80
            HTTPS_EXPOSE: 8142:80
            TZ: America/Los_Angeles
            VIRTUAL_HOST: borg.ddev.site
            XHGUI_PDO_PASS: db
            XHGUI_PDO_USER: db
            XHGUI_SAVE_HANDLER: pdo
        image: ddev/ddev-xhgui:v1.24.4
        labels:
            com.ddev.approot: /Users/jlampton/Sites/_backdrop/backdropcms.org/repo
            com.ddev.site-name: borg
        links:
            - db
        networks:
            ddev_default: null
            default: null
        profiles:
            - xhgui
        restart: "no"
volumes:
    database:
        external: true
        name: borg-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
    project_mutagen:
        external: true
        name: borg_project_mutagen
